base_url = "https://figbert.com"
title = "FIGBERT"
description = "world wide web benji-style"
author = "Benji Welner"

default_language = "en"
generate_feeds = true
minify_html = true

[markdown]
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true

[markdown.highlighting]
light_theme = "github-light"
dark_theme = "github-dark"
